### ISSUE TITLE
VL53L1X running slow during live acquisition. Need to check on that.

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/roboskin#26]
The title explains it all.

**Comment by krishnachaitanya7** [comment]
Hi @calebescobedo, I had this issue when I was doing the testing at that time. Kindly lemme know if you are facing any similar issue, we can try to solve it.

**Comment by calebescobedo** [comment]
Can you please try to change it according to this?
![image](https://user-images.githubusercontent.com/37485219/75599356-4f7ad900-5a61-11ea-92f6-974f7582fdf7.png)

**Comment by watakandai** [comment]
Is this solved? If so could you post the solution? 
Thanks

**Comment by krishnachaitanya7** [comment]
Raised PR #54, should be good now. Closing this issue.

**Comment by krishnachaitanya7** [comment]
PR #54 wasn't good enough. The whole problem is addressed in PR #56. I hope that helps. Thank you.
