### ISSUE TITLE
Pylint Integration

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/roboskin#28]
As we have started collaborating on the repo with many people pushing commits, Pylint is more than necessary for the code quality.

**Comment by watakandai** [comment]
I certainly agree. @peasant98 can you work on this !?

**Comment by krishnachaitanya7** [comment]
We need to come up with good practices so that Pylint scans the whole repo for errors. @peasant98 please help me out here, you're an expert in this!

**Comment by krishnachaitanya7** [comment]
Also, it would be great if we integrate PyType: https://google.github.io/pytype/. Another work would be to maintain and install all these tools across the PC's in VSCode
