### ISSUE TITLE
Question About Dockerfile

### ISSUE THREAD

**Issue by peasant98** [HIRO-group/roboskin#32]
Hi all, 

Do we need Dockerfile currently?

**Comment by calebescobedo** [comment]
I don't think anyone is currently using Docker to run the robot skin code.

What made you think of making a Dockerfile? Do you think we should start making one?

**Comment by peasant98** [comment]
Hmm, I think if we open source it, it could be of good use to other folks who want to dip their toes into this subject.

**Comment by peasant98** [comment]
closing this as we will discuss it after the first project is done.

**Comment by krishnachaitanya7** [comment]
I think your idea of creating a docker is a good one, but we should come up with some way to run in Armhf boards too, we need to look into docker buildx

**Comment by krishnachaitanya7** [comment]
Okay I was seeing about this: https://docs.docker.com/buildx/working-with-buildx/. There is one more alternate way to copy qemu libraries into the docker container and then try to build on Intel. I don't like that way, also docker is very susceptible to exit codes and qemu sometimes throws many warnings which might break the building of container on intel machines. Lemme know your view

**Comment by krishnachaitanya7** [comment]
@peasant98 maybe this is that good time to start working on it.

**Comment by watakandai** [comment]
https://github.com/Tiryoh/docker_ros-desktop-vnc

**Comment by watakandai** [comment]
This repo should work perfectly.

**Comment by peasant98** [comment]
Alright. I will work on it toda.

**Comment by watakandai** [comment]
oh this was not `ros_robotic_skin`. Then we don't need a docker for ros don't we? Just a simple python environment is enough.

**Comment by krishnachaitanya7** [comment]
Making a ROS docker would be good as that will ensure all imports, library install instructions are good or not.

**Comment by krishnachaitanya7** [comment]
But for the most part, it's kinda not useful, we have to make an RPi server which will receive CI instructions with all the sensors attached. People have done that. Doing that would be great.

**Comment by peasant98** [comment]
This is done
