### ISSUE TITLE
Pylint giving so many errors

### ISSUE THREAD

**Issue by watakandai** [HIRO-group/roboskin#34]
@peasant98 Could you go through the PyLint Errors and fix them? 
If it's too much work, let us know. 
We will divide the work and fix them as a team.

**Comment by peasant98** [comment]
Yes.

**Comment by krishnachaitanya7** [comment]
I will fix every file name starting with lsm6ds3 and vl53l1x, as I have coded them, but they should be having fewer errors, but whatever they are I will fix them tomorrow

**Comment by watakandai** [comment]
Danke schone!!!!!!

**Comment by peasant98** [comment]
A PR has been raised addressing this issue at #35

**Comment by krishnachaitanya7** [comment]
Please make sure to mention Issues in PR main comment, so that we know the action has been taken. Please and Thank you.
