### ISSUE TITLE
dot product to matmul

### ISSUE THREAD

**Issue by watakandai** [HIRO-group/roboskin#36]
We need (?) or would be nice if we have "@" operator for the dot product so that the equation would look simple

https://github.com/HIRO-group/robotic_skin/blob/fade513b303e4c948752ae5d5bf2ccdd278656a5/robotic_skin/calibration/utils.py#L113

**Comment by krishnachaitanya7** [comment]
That's a great Idea. Here is the PEP: https://www.python.org/dev/peps/pep-0465/.  So @ operator isn't in Python2, that might be the only problem. Would we be running the algorithm in Python3?

**Comment by watakandai** [comment]
No. We also assume to run with Python2. Then dot product might be better lol

**Comment by krishnachaitanya7** [comment]
I can feel you.

![2uzxes](https://user-images.githubusercontent.com/9385832/73813249-ac55dd00-479c-11ea-8b43-0a7024dfedab.jpg)
