### ISSUE TITLE
Remove vcnl files, as we removed requirements

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/roboskin#43]
If it's possible to remove the files 08_plot_vcnl4040.py and 07_read_vcnl4040.py as some of its requirements have been removed to enable python install in Python2.7 environment. There can be two ways:
- Ignore both files from PyLint
- Delete those files

@peasant98 can you please look into if this is possible? Thanks!

**Comment by watakandai** [comment]
i will delete the examples

**Comment by krishnachaitanya7** [comment]
I prefer ignoring them. Why delete they can be useful in future?

**Comment by krishnachaitanya7** [comment]
I guess we can close this now.
