### ISSUE TITLE
Setting Environment variables in python files itself for communicating with ROS master

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/roboskin#55]
In my blog here: https://krishnachaitanya9.github.io/posts/ros_publish_subscribe/ I have added many environment variables that need to be set successfully for everything to work correctly. Making this an issue so that I can keep track of it.

**Comment by alecive** [comment]
Environment variables should not be set in python files. Environment variables should be set in your bashrc. If things change, you don't want to change 20 thousand files scattered on 50 machines, but only the 50 machines.

**Comment by watakandai** [comment]
Please write the tutorials on the GitHub Wiki and not on your blog. 
You CAN write the same one on your blog but always wiki first.

**Comment by krishnachaitanya7** [comment]
@alecive So I am setting the environment variables from python for two main reasons:
- If I have to communicate with 2 ROS masters. That is the case when one proximity is connected to bus-1, and I want proximity data to be sent to HIRO Lab PC's so that I can see graphs there. Next, I connected accelerometer to bus 0, and I was sending the IMU msgs to my laptop to do Pose estimation as much of the code and environment is on my laptop. If I had used bashrc, I would have needed to change very often. But as I am setting them as environment variables in python, they are just set for my python process but not for the whole environment.
- It's an excellent point that if I make a variable in the python file, then I would have to change it every time. That might cause someone to make useless commits to Github. Hence the idea Kandai and I have come up with is to pass the config file as an argument. Now, this also suffers from the problem of changing multiple times.  For this, I added a sample file in git, which acts as a template for each user. Then the user has to make his config file from the template, which is by default gitignored. For example, sample_publisher_variables.yaml is the sample file, publisher_variables.yaml is the yaml each user has to make on his own, which is by default gitignored.
- The yaml file gives total flexibility to user to implement whichever custom configurations and a one-stop solution to custom configurations, without needing to go to bashrc and look up why something is not working. 

Thank you!

**Comment by krishnachaitanya7** [comment]
@watakandai Sure I will do it first. Thank you!

**Comment by krishnachaitanya7** [comment]
> @alecive So I am setting the environment variables from python for two main reasons:
> 
> * If I have to communicate with 2 ROS masters. That is the case when one proximity is connected to bus-1, and I want proximity data to be sent to HIRO Lab PC's so that I can see graphs there. Next, I connected accelerometer to bus 0, and I was sending the IMU msgs to my laptop to do Pose estimation as much of the code and environment is on my laptop. If I had used bashrc, I would have needed to change very often. But as I am setting them as environment variables in python, they are just set for my python process but not for the whole environment.
> * It's an excellent point that if I make a variable in the python file, then I would have to change it every time. That might cause someone to make useless commits to Github. Hence the idea Kandai and I have come up with is to pass the config file as an argument. Now, this also suffers from the problem of changing multiple times.  For this, I added a sample file in git, which acts as a template for each user. Then the user has to make his config file from the template, which is by default gitignored. For example, sample_publisher_variables.yaml is the sample file, publisher_variables.yaml is the yaml each user has to make on his own, which is by default gitignored.
> * The yaml file gives total flexibility to user to implement whichever custom configurations and a one-stop solution to custom configurations, without needing to go to bashrc and look up why something is not working.
> 
> Thank you!

@alecive can you please give me your view on this? Thank you!

**Comment by alecive** [comment]
- I don't see why you should have two ROS Masters -- there should only be one. Where are these masters located again? one on your pc and one on your laptop? If so, there should be only one
- ROS is meant to be distributed and not tied to specific machines--it doesn't matter if your code runs on your laptop or on a raspberry pi on the moon AS LONG AS your ONLY ROS master is aware of it.
- Local configuration variables should be local to the machine and never committed to GH. Your GH repo should be generic and broadly usable by people, and your local configs (in terms of IPs and also whatever file is customized to your specific setup) should be local to the machine. 
- Launch files are usually used in ROS to implement what you are doing as a custom thing in yaml. The launch file sets the variables and then you can read them as ROS params.

**Comment by krishnachaitanya7** [comment]
Sure. Thank you so much for the insight.
