### ISSUE TITLE
Sphinx requires Python>=3.5 But Python2.7 was Given

### ISSUE THREAD

**Issue by krishnachaitanya7** [HIRO-group/roboskin#62]
![image](https://user-images.githubusercontent.com/9385832/77032161-49459180-6969-11ea-91c6-739676b95eda.png)
The title explains it all

**Comment by watakandai** [comment]
Just run with python3

**Comment by krishnachaitanya7** [comment]
It's actually in the requirements.txt. So I gotta remove it so that the pip install will be successful all times.

**Comment by peasant98** [comment]
Ya, the package is for python3. So we should specify that the user should be using the pip associated with python3.

**Comment by peasant98** [comment]
fixed.
